# Generated by Django 4.2.7 on 2023-12-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_contact_contact_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default='', max_length=300),
        ),
    ]
